[package]
name = "archlinux-driver-manager"
version = "0.0.1"
edition = "2021"
license = "MPL-2.0"
authors = ["shivanandvp <shivanandvp.oss@gmail.com, shivanandvp@rebornos.org>"]
readme = "README.md"
repository = "https://gitlab.com/shivanandvp/archlinux-driver-manager.git"
description = "A driver manager for Arch Linux"
# documentation = "https://docs.rs/archlinux-driver-manager"
keywords = ["driver", "drivers", "hardware", "arch"]
categories = ["command-line-utilities"]
exclude = ["scripts/*", ".gitlab-ci.yml", "ArchLinuxDriverManager.code-workspace"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# For the Commandline
clap = { version = "3.1", features = ["derive"] }
qr_code = { version = "1.1" }
owo-colors = { version = "3.3", features = ["supports-colors"] }

# Miscellaneous
snafu = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustbreak = { version = "2", features = ["ron_enc"] }
rangemap = { version = "1.0", features = ["serde1"] }
